--
-- File generated with SQLiteStudio v3.2.1 on sex mar 27 19:57:51 2020
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: TIMESHEET
DROP TABLE IF EXISTS TIMESHEET;

CREATE TABLE TIMESHEET (
    ID_TIMESHEET INTEGER PRIMARY KEY AUTOINCREMENT,
    DATE_RG      DATE    NOT NULL,
    START_AM     TIME,
    END_AM       TIME,
    START_PM     TIME,
    END_PM       TIME,
    DESCRIPTION  TEXT
);

DROP TABLE IF EXISTS TASK;

CREATE TABLE TASK (
    ID_TASK      INTEGER PRIMARY KEY AUTOINCREMENT
                         NOT NULL,
    START_TM     TIME    NOT NULL,
    END_TM       TIME    NOT NULL,
    DESCRIPTION  TEXT    NOT NULL,	
	INDICE_PROJECT VARCHAR(10) NOT NULL,
    ID_TIMESHEET INTEGER NOT NULL,
    ID_PROJECT   INTEGER
);

DROP TABLE IF EXISTS PROJECT;

CREATE TABLE PROJECT (
    ID_PROJECT  INTEGER       PRIMARY KEY AUTOINCREMENT NOT NULL,                             
    START_DT    DATETIME      NOT NULL,
    END_DT      DATETIME,
	NAME		VARCHAR(1000) NOT NULL,
	ALIAS		VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR (500) NOT NULL
);

DROP TABLE IF EXISTS PARAMETER;

CREATE TABLE PARAMETER (
    [KEY] STRING (100) NOT NULL UNIQUE ,
    VALUE TEXT
);

DROP TABLE IF EXISTS SETTINGS;

CREATE TABLE SETTINGS (
    KEY STRING (100) NOT NULL UNIQUE,
    VALUE TEXT
);

DROP TABLE IF EXISTS SYNCRONISM;

CREATE TABLE SYNCRONISM (
    TABLENAME STRING (20) NOT NULL,
    OPERATION INTEGER NOT NULL,
	DATA TEXT NOT NULL,
	DATE_MODIFICATION DATETIME 
);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
